#!/bin/bash

echo "=== 持续按键控制演示 ==="
echo ""
echo "这个演示展示了如何使用WASD键进行持续按键控制："
echo ""
echo "控制说明："
echo "  W - 前进 (速度: 0.5)"
echo "  S - 后退 (速度: 0.5)"
echo "  A - 左移 (速度: 0.5)"
echo "  D - 右移 (速度: 0.5)"
echo "  Q - 左转 (角度: -π/4)"
echo "  E - 右转 (角度: π/4)"
echo "  空格 - 切换调试模式"
echo ""
echo "运行主程序来测试持续按键功能："
echo "cd build && export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:\$LD_LIBRARY_PATH && ./Lite_motion"
echo ""
echo "或者运行键盘控制器测试："
echo "cd build && ./test_keyboard_controller"
echo ""
echo "按任意键继续..."
read -n 1

echo ""
echo "=== 功能特点 ==="
echo "1. 持续按键检测 - 按住按键会持续触发动作"
echo "2. 多按键支持 - 可以同时按下多个按键"
echo "3. 实时响应 - 按键状态实时更新"
echo "4. 非阻塞输入 - 不会阻塞主程序运行"
echo ""
echo "=== 实现原理 ==="
echo "1. 使用termios设置终端为非阻塞模式"
echo "2. 使用select()检测输入事件"
echo "3. 维护按键状态映射表"
echo "4. 在主循环中持续检查按键状态"
echo ""
echo "演示完成！" 